spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/usermanagement
    username: root
    password: Iresh@123
    
  jpa:
    properties:
      show-sql: true
      format-sql: true
      
  boot:
    admin:
      client:
        url: http://localhost:1111/
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
      
management:
  endpoints:
    web:
      exposure:
        include: '*'
spring:
  mail:
    host: smtp.gmail.com
    port: 587
    username: cab128864@gmail.com
    password: anzk neua plwp vquz
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

      
